#!/usr/bin/python
# -*- coding: utf-8 -*-

import shutil
import errno
import subprocess

__author__ = "Phil Huang"
__email__ = "phil_huang@edge-core.com"

MACHINE_NAME = "AS5712"  # TODO: Detect from onl-sysconfig
TAR_NAME = "onl-support-" + MACHINE_NAME
TAR_ROOT = "/tmp/" + TAR_NAME
COMMAND_ROOT = TAR_ROOT + "/support/"


def copy_dir(src):
    dest = TAR_ROOT + src
    try:
        shutil.copytree(src, dest)
    except OSError as e:
        if e.errno == errno.ENOTDIR:
            shutil.copy(src, dest)
        else:
            print('Directory not copied. Error: %s' % e)


def dump_command(command):
    output = COMMAND_ROOT + command
    proc = subprocess.Popen(command,
                            stdout=output,
                            stderr=subprocess.PIPE)
    # for line in proc.stderr:
    #     output.wirte(line)
    proc.wait()


if __name__ == '__main__':
    copy_dir("/etc")
    copy_dir("/var")
    dump_command("onl-sysconfig")
